version: '3.8'

services:
  chromadb:
    image: chromadb/chroma
    container_name: chromadb
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/chroma
    restart: always

  # postgres:
  #   image: postgres:latest
  #   container_name: postgres_db
  #   environment:
  #     POSTGRES_USER: user
  #     POSTGRES_PASSWORD: password
  #     POSTGRES_DB: mydatabase
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - pg_data:/var/lib/postgresql/data
  #   restart: always

  # agno-agent:
  #   build: ./agno  # Si tienes un Dockerfile en la carpeta ./agno
  #   container_name: agno_agent
  #   depends_on:
  #     - chromadb
  #     - postgres
  #   environment:
  #     DATABASE_URL: postgresql://user:password@postgres_db:5432/mydatabase
  #     CHROMA_DB_URL: http://chromadb:8000
  #   ports:
  #     - "5000:5000"
  # restart: always

volumes:
  chroma_data:
  pg_data:
